services:
  - type: web
    name: evoting-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings_production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SEED_ADMIN
        value: true
      - key: ALLOWED_HOSTS
        value: evoting-system-h779.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://evoting-system-rho.vercel.app
      - key: DEBUG
        value: false
      - key: AUTO_MIGRATE
        value: true
      - key: IMPORT_LOCAL_DATA
        value: true
    # PostgreSQL database URL
    - key: DATABASE_URL
      fromDatabase:
        name: evoting-db
        property: connectionString

  - type: pserv
    name: evoting-db
    env: postgresql
    plan: free
    ipAllowList: []
